global:
  scrape_interval: 5s

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: market-data
    static_configs:
      - targets: ["market-data:8011"]
  - job_name: workflow-api
    static_configs:
      - targets: ["workflow-api:8012"]
  - job_name: genai-api
    static_configs:
      - targets: ["genai-api:8013"]
  - job_name: rag-api
    static_configs:
      - targets: ["rag-api:8014"]
  - job_name: agent-controller
    static_configs:
      - targets: ["agent-controller:8015"]
  - job_name: mcp-server
    static_configs:
      - targets: ["mcp-server:8016"]
