apiVersion: v1
kind: Namespace
metadata:
  name: tradeops
  labels:
    app.kubernetes.io/part-of: tradeops
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
