apiVersion: v1
kind: ResourceQuota
metadata:
  name: tradeops-runtime
  namespace: tradeops
spec:
  hard:
    requests.cpu: "6"
    requests.memory: 10Gi
    limits.cpu: "16"
    limits.memory: 24Gi
    persistentvolumeclaims: "8"
    requests.storage: 20Gi
