{{ if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels:
    {{- include "tradeops.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{ end }}
