apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tradeops-platform
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: tradeops
  source:
    repoURL: https://github.com/zdmooc/TradeOps-GenAI-Integration.git
    targetRevision: main
    path: infra/openshift/overlays/crc
  destination:
    server: https://kubernetes.default.svc
    namespace: tradeops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
